:- use_module(library(scasp)).
:- use_module(library(http/json)).
player_seen.
noise(unknown).
broken_vase(unknown).
broken_vase(unknown).
alarm_raised.
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
broken_vase(unknown).
